version: '3.9'

x-app: &default-app
  restart: always

services:
  postgres:
    restart: always
    image: postgres
    container_name: postgres-composed
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=develop
    volumes:
      - ./initPataviDB.sh:/docker-entrypoint-initdb.d/initPataviDB.sh

  rabbit:
    restart: always
    image: rabbitmq:3-management
    container_name: rabbit-composed
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 60s
      timeout: 3s
      start_period: 10s
      retries: 5

  patavi-server-composed:
    restart: always
    image: registry.drugis.org/patavi-server:composed
    container_name: patavi-server-composed
    ports:
      - 3000:3000
    depends_on:
      - postgres
      - rabbit
    environment:
      - PATAVI_BROKER_HOST=rabbit
      - PATAVI_DB_HOST=postgres
      - PATAVI_DB_NAME=patavi
      - PATAVI_DB_PASSWORD=develop
      - PATAVI_DB_USER=patavi
      - PATAVI_PORT=3000
      - SECURE_TRAFFIC=false
      - PATAVI_API_KEY=someApiKey

networks:
  default:
    name: patavi-composed-network
