name: Patavi-server develop | push | deploy

on:
  push:
    branches: develop

defaults:
  run:
    working-directory: './server'

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: ['18']
        os: [ubuntu-22.04]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.OS }}-build-${{ hashFiles('package.json') }}

      - name: run yarn
        run: yarn

      # - name: docker login
      #   run: docker login -u addis -p ${{ secrets.dockerRegistryPassword }}

      # - name: build patavi server image
      #   run: cd docker && docker build --tag addis/patavi-server:test --build-arg sha=`git rev-parse --short HEAD` .

      # - name: docker push patavi server image
      #   run: docker push addis/patavi-server:test

      - name: pull server image on server
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.devJumpHost }}
          username: ${{ secrets.devJumpHostUser }}
          key: ${{ secrets.deployPrivateKey }}
          proxy_host: ${{ secrets.devInternalServer }}
          proxy_username: ${{ secrets.devInternalUser }}
          proxy_key: ${{ secrets.deployPrivateKey }}
          script: ls -al
          debug: true

      # - name: remove patavi server container on the server
      #   run:
      #     ssh -J ${{ secrets.devJumpHost }} ${{ secrets.devInternalServer }} \
      #     "if  systemctl list-unit-files | grep patavi-server
      #     then
      #     systemctl stop patavi-server
      #     systemctl disable patavi-server
      #     rm -f /etc/systemd/system/patavi-server.service
      #     systemctl daemon-reload
      #     podman rm patavi-server
      #     fi"

      # - name: run patavi server container on the server
      #   run: >
      #     ssh -J ${{ secrets.devJumpHost }} ${{ secrets.devInternalServer }} \
      #     "podman run -d \
      #       --network="slirp4netns:allow_host_loopback=true" \
      #       --restart on-failure \
      #       -e PATAVI_BROKER_HOST=guest:guest@10.0.2.2 \
      #       -e PATAVI_PROXY_HOST=patavi.dev.drugis.org \
      #       -e BEHIND_PROXY=true \
      #       -e PATAVI_PORT=3000 \
      #       -e PATAVI_DB_HOST=10.0.2.2 \
      #       -e PATAVI_DB_NAME=patavi \
      #       -e PATAVI_DB_USER=patavi \
      #       -e PATAVI_DB_PASSWORD=${{ secrets.pataviDbPassword }} \
      #       -e SECURE_TRAFFIC=false \
      #       -e PATAVI_API_KEY=${{ secrets.pataviApiKey }} \
      #       -p 3000:3000 \
      #       --name patavi-server \
      #       addis/patavi-server:test"

      # - name: generate system service file
      #   run: >
      #     ssh -J ${{ secrets.devJumpHost }} ${{ secrets.devInternalServer }} \
      #     'podman generate systemd --name patavi-server > /etc/systemd/system/patavi-server.service'

      # - name: stop patavi server container
      #   run: >
      #     ssh -J ${{ secrets.devJumpHost }} ${{ secrets.devInternalServer }} \
      #     'podman stop patavi-server'

      # - name: stop patavi server container
      #   run: >
      #     ssh -J ${{ secrets.devJumpHost }} ${{ secrets.devInternalServer }} \
      #     "systemctl daemon-reload && \
      #       systemctl enable patavi-server && \
      #       systemctl enable patavi-server"

      - name: notify on slack channel on failure
        if: failure()
        uses: rtCamp/action-slack-notify@master
        env:
          SLACK_WEBHOOK: ${{ secrets.slackWebhook }}
          SLACK_USERNAME: gitbot
          SLACK_TITLE: 'Develop push:'
          SLACK_MESSAGE: 'patavi-test deploy failed'

      - name: notify on slack channel on success
        uses: rtCamp/action-slack-notify@master
        env:
          SLACK_WEBHOOK: ${{ secrets.slackWebhook }}
          SLACK_USERNAME: gitbot
          SLACK_TITLE: 'Develop push:'
          SLACK_MESSAGE: 'patavi-test deployed'
