name: Patavi | push | worker build & push

on:
  push:
    branches: 'master'

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-22.04]

    steps:
      - uses: actions/checkout@v3

      - name: build worker uberjar
        run: |
          cd worker
          lein uberjar
          cp target/patavi.worker-0.3-standalone.jar docker/
          cd ..

      - name: build docker image
        run: |
          cd worker/docker
          docker build --tag addis/patavi-worker-base .

      - name: docker login
        run: docker login -u addis -p ${{ secrets.dockerRegistryPassword }}

      - name: docker push
        run: docker push addis/patavi-worker-base
